### ISSUE TITLE
Removing the requirement to call JSX.register

### ISSUE THREAD

**Issue by natecavanaugh** [metal/metal-jsx#1]
Heya Maira,
This repo is really cool! Thanks for working on it :)

There was one aspect I'm not a huge fan of is needing to call `JSX.register` on a created component.

What would you think about exporting a Component from this that extends from `metal-component`, but that in the constructor automatically registers it with the JSX renderer?

Of course, I haven't tested any of this, so I don't know for sure if it would even work, but it might be worth a look :)

**Comment by mairatma** [comment]
Right now unfortunately that wouldn't work, because we need to register the component before it's even instantiated for the first time, so that other components can call it via nested components (for example: `<MyComponent/>`.

The reason why we need this before the constructor call is that this nested components feature is currently implemented using the component's name, so `<MyComponent/>` would be compiled to `IncrementalDOM.elementOpen('MyComponent')`. We need a way to figure out which class is associated with a given name, even if it has never been used before, and so that association is done via `JSX.register`.

We use [babel-plugin-incremental-dom](http://npmjs.com/package/babel-plugin-incremental-dom) for the jsx to incremental dom compilation, and they do have an [issue](https://github.com/jridgewell/babel-plugin-incremental-dom/issues/9) open for dealing with this use case. Once they fix it we can remove this requirement from JSX components by doing something similar to what you've proposed :)

**Comment by natecavanaugh** [comment]
Heya Maira,
Thanks for the response, and I *think* I understand (though please correct me if my response below either doesn't make sense, or the example I'm using doesn't apply).

If we need the info at definition time, I almost wonder, what if we used the "higher-order component" method that Dan Abramov [described here](https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750)? The main relevant code could be seen in [this gist](https://gist.github.com/sebmarkbage/ef0bf1f338a7182b6775).

But the idea, as I understand it, is wrapping the class and extending it and performing the actions it needs.

And now that I'm typing all of this up, I'm realizing it is a little bit of "6 of one, half a dozen of the other" type thing.
But maybe the only difference is, instead of treating it as a static method, it would be an enhance method that returns the component *and* registers it.

Thinking about it, it might look something [like this](https://gist.github.com/natecavanaugh/905d863867a03b6e0289f24aa591b5d9) (an example in both the Modal and the JSX module).

Of course, that would also mean the state and other static properties would have to be copied, and of course, it could just not work (since it's somewhat of an indirection, and the compiler might still not be able to work with it).

But just an idea, in case we wished to one day add other behavior or manipulation just for JSX based components.
But yeah, I guess ideally for this scenario, we wouldn't even need that.

What I like about the composition one, though, is that since the JSX component is already importing metal-component, it doesn't need to be imported in the Modal.

But now having typed it all out, I understand a bit more the limitations, so I can live with both if needed, but let me know what you think about the examples (if they could or wouldn't work).

**Comment by mairatma** [comment]
Yeah, I also like the high-order component idea, it can be very useful in many cases. As you said though, in this case it wouldn't make much of a difference, it would still be a function that you need to call passing the component, the only difference being that it would also return another component.

In the end I think it would just be more boilerplate for this use case, both for the implementation of this function (which would now create another component and return it, even though it doesn't need this kind of composition, as well as copy over any statics) and for the user (which would need to export the returned component instead of their own).

Also, the implementation you sent would not actually work, because there would be no component registered with the name `ComposedComponent`, since the `JSX.register` call would have registered the component with its original function name (`Modal` in your example). We could definitely make this work though, it would just need more code.

As said, we'll also be able to remove this function altogether once the compiler is improved, so it will be even better then :)

**Comment by mairatma** [comment]
Just FYI, I've just managed to make the change we needed so we could get rid of JSX.register, I'll update the components we have accordingly :)
