### ISSUE TITLE
Enable the use of property initializers in Babel

### ISSUE THREAD

**Issue by natecavanaugh** [metal/metal-jsx#2]
Heya Maira,
I'm not sure if this is the right project to submit this to (since you may wish to have the flag set more than for just this repo).

But I recently had found that it's discouraged from using arrow functions and `.bind(this)` calls inside of render.
The main reason is because it increases memory usage as well as excessively hammers the garbage collector.
You can [read about it here](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md).

The way they describe getting around that is to use property initializers, however, they're a stage 1 setting.

But the final product looks something like:

```js
class Foo extends JSXComponent {
    hide = () => {
        this.visible = false;
    }

    render() {
        return <div data-onclick={this.hide}></div>;
    }
}
```

Is enabling that something we can do?

Thanks Maira!

**Comment by mairatma** [comment]
You're right, binding functions every time can be bad for performance.

There are ways to go around this without needing stage 1 though, as explained [here](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md#es6-classes).

I agree that your example is nicer, but since stage 1's features are not as stable as the main es6 ones I'd prefer that we avoid using it on Metal.js by default. Instead we could make it easy for people to customize the build processes we have to use any babel plugins they wish, including the one for enabling stages, so I'll add an option for that on [gulp-metal](http://npmjs.com/package/gulp-metal) and [metal-cli](http://npmjs.com/package/metal-cli). If they use a separate build process then they can already do this. That way we can keep our core with only the most stable features, while allowing anyone to choose for themselves. What do you think?

**Comment by natecavanaugh** [comment]
Heya Maira,
I think enabling the ability to use the option would be a good one to consider.

Though I'm not sure about using another build system (It's kind of a nightmare from what I can tell, but I'll open up a separate ticket about it :))

**Comment by mairatma** [comment]
I've created tickets on our 2 build tools: [gulp-metal](https://github.com/metal/gulp-metal/issues/14) and [metal-cli](https://github.com/metal/metal-cli/issues/1), since that's where the option needs to be. I'll close this since it will be handled there :)
